# Generated by Django 3.2.16 on 2022-10-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221019_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='id',
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
