# Generated by Django 3.2.16 on 2022-10-19 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221019_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='medal',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='id',
        ),
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drone')),
                ('medications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medication')),
            ],
        ),
    ]
