# Generated by Django 3.2.16 on 2022-10-19 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221019_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='id',
            new_name='package_id',
        ),
    ]
