# Generated by Django 3.2.16 on 2022-10-19 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221019_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drone')),
                ('medications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medication')),
            ],
        ),
    ]
