# Generated by Django 3.2.16 on 2022-10-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='medal',
            new_name='model',
        ),
    ]
