# Generated by Django 4.0.7 on 2022-11-03 20:08

import api.models.drone
import api.models.medication
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_batterylevelhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='weight_limit',
            field=models.IntegerField(validators=[api.models.drone.validate_weight_limit]),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=100, validators=[api.models.medication.validate_name]),
        ),
    ]
