# Generated by Django 4.0.7 on 2022-11-03 20:57

import api.models.drone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_drone_weight_limit_alter_medication_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='battery_capacity',
            field=models.FloatField(validators=[api.models.drone.validate_battery_capacity]),
        ),
    ]
