# Generated by Django 4.0.7 on 2022-11-05 15:16

import api.models.medication
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_drone_battery_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, validators=[api.models.medication.validate_code]),
        ),
    ]
